language: ruby

# We deviate from the rspec-dev cache setting here.
#
# Travis has special bundler support where it knows to run `bundle clean`
# before backing up the bundle so it doesn't grow indefinitely.
#
# For the other repos we changed to specifying the directory specifically to
# avoid the `bundle clean` travis was doing, because Myron found that, when
# running one of the a build for one repo, the "run the rspec-core and
# rspec-rails spec suites" parts would take a while because it would _always_
# have to install fresh gems (they weren't in the cache). This was happening
# because travis was running `bundle clean` (due to the previous `cache:
# bundler` config) against one repo which was was pruning gems installed for
# the other repos.
#
# In our case, we aren't running the spec suites for the other repos so the
# original `cache: bundler` is a better option.
cache: bundler

bundler_args: "--binstubs --path ../bundle --retry=3 --jobs=3"

before_install:
  - script/update_rubygems_and_install_bundler
  - script/downgrade_bundler_on_old_rails
  - script/clone_all_rspec_repos

before_script:
  # Rails 4.x complains with a bundler rails binstub in PROJECT_ROOT/bin/
  - rm -f bin/rails
  - bundle exec rails --version

script: "script/run_build 2>&1"

matrix:
  include:
    # Rails dev / 6 builds >= 2.4.4
    - rvm: jruby-head
      env:
        - RAILS_VERSION=master
        - JRUBY_OPT=--dev

  fast_finish: true

branches:
  only:
    - master
    - /^\d+-\d+-maintenance$/
